# Hangar Service configuration
spring.application.name=hangar-service
server.port=8082

# Database connection.
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:hangar_db}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:hangar_user}
spring.datasource.password=${DB_PASSWORD:changeme}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


aircraft.service.url=${AIRCRAFT_SERVICE_URL:http://localhost:8081}
